test: fix failing TestEventLogger on Windows
--- FAIL: TestEventLogger (1.57s)
    testing.go:1206: TempDir RemoveAll cleanup: remove C:\Users\ContainerAdministrator\AppData\Local\Temp\TestEventLogger1063540432\001\bookmark.xml: The process cannot access the file because it is being used by another process.

Signed-off-by: Eng Zer Jun <engzerjun@gmail.com>