river/vm: improve error messages for invalid field names
This changes errors such as

  Error: ./cmd/agent/example-config.river:16:21: field "kontent" does not exist

  15 |         "__address__"   = "demo.robustperception.io:9090",
  16 |         "dynamic_label" = local.file.this_file.kontent,
     |                           ^^^^^^^^^^^^^^^^^^^^
  17 |     }]

into the more expected form

  Error: ./cmd/agent/example-config.river:16:42: field "kontent" does not exist

  15 |         "__address__"   = "demo.robustperception.io:9090",
  16 |         "dynamic_label" = local.file.this_file.kontent,
     |                                                ^^^^^^^
  17 |     }]

Test are not changed because the changes here should be self-evident.