test: fix failing TestStorage_DuplicateExemplarsIgnored on Windows
--- FAIL: TestStorage_DuplicateExemplarsIgnored (1.54s)
    testing.go:1206: TempDir RemoveAll cleanup: remove C:\Users\ContainerAdministrator\AppData\Local\Temp\TestStorage_DuplicateExemplarsIgnored3557982825\001\wal\00000000: The process cannot access the file because it is being used by another process.

Signed-off-by: Eng Zer Jun <engzerjun@gmail.com>